const REQUEST_TRANSITIONS={pending:['under_review'],under_review:['approved','rejected'],approved:['ready_for_pickup']};
const CONCERN_TRANSITIONS={open:['in_progress'],in_progress:['resolved']};
const REQUEST_STATUS_LABEL={pending:'Pending',under_review:'Under review',approved:'Approved',rejected:'Rejected',ready_for_pickup:'Ready for pickup',completed:'Completed'};
const CONCERN_STATUS_LABEL={open:'Open',in_progress:'In progress',resolved:'Resolved',closed:'Closed'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v?new Date(v).toLocaleString():'—';
const dateOnly=v=>v?new Date(v).toLocaleDateString():'—';
function showAlert(message,tone){const box=document.getElementById('admin-alert');box.textContent=message;box.className=`page-alert page-alert--${tone}`;box.hidden=false;clearTimeout(showAlert._t);showAlert._t=setTimeout(()=>box.hidden=true,4000);}
function transitionOptions(current,transitions,labelMap){return[current,...(transitions[current]||[])].map(v=>`<option value="${esc(v)}">${esc(labelMap[v]||v)}</option>`).join('');}
function historyButton(module,id){return`<button type="button" class="btn btn--ghost" data-history-module="${esc(module)}" data-history-id="${esc(id)}">View History</button>`;}
let activePanel='dashboard';
function showPanel(name){activePanel=name;document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==name);document.querySelectorAll('.portal-nav__item').forEach(b=>b.classList.toggle('portal-nav__item--active',b.dataset.nav===name));const panel=document.querySelector(`[data-panel="${CSS.escape(name)}"]`);if(panel)panel.scrollIntoView({block:'start'});}
async function loadDashboard(){try{document.getElementById('requests-loading').hidden=false;document.getElementById('concerns-loading').hidden=false;const[summary,requests,concerns]=await Promise.all([getAdminSummary(),getAdminRequests(),getAdminConcerns()]);const s=summary.summary||{},req=s.requestsByStatus||[],con=s.concernsByStatus||[];document.getElementById('metric-users').textContent=s.totalUsers??0;document.getElementById('metric-requests').textContent=req.reduce((a,x)=>a+x.count,0);document.getElementById('metric-pending').textContent=req.find(x=>x._id==='pending')?.count||0;document.getElementById('metric-concerns').textContent=con.filter(x=>!['resolved','closed'].includes(x._id)).reduce((a,x)=>a+x.count,0);renderRequests(requests.requests||[]);renderConcerns(concerns.concerns||[]);}catch(e){if(e.status===401||e.status===403)clearSession();showAlert(e.message,'error');}finally{document.getElementById('requests-loading').hidden=true;document.getElementById('concerns-loading').hidden=true;}}
function renderRequests(rows){document.getElementById('requests-body').innerHTML=rows.length?rows.map(r=>`<tr data-record-row="requests:${esc(r.id)}"><td>${esc(r.requestor?.fullName||'Unknown')}<br><span class="hint" style="margin:0">${esc(r.requestor?.email||'')}</span></td><td>${esc(r.documentType)}<br><span class="hint">${esc(r.trackingNumber||'')}</span></td><td>${esc(r.purpose)}</td><td>${fmt(r.createdAt)}</td><td><select class="status-control" data-request-status="${esc(r.id)}" data-current="${esc(r.status)}">${transitionOptions(r.status,REQUEST_TRANSITIONS,REQUEST_STATUS_LABEL)}</select></td><td><input class="status-note" data-request-note="${esc(r.id)}" placeholder="Note (required if rejecting)"></td><td>${historyButton('requests',r.id)}</td><td><button type="button" class="btn btn--green" data-save-request="${esc(r.id)}">Save</button></td></tr>`).join(''):'<tr><td colspan="8" class="empty-row">No document requests yet.</td></tr>';}
function renderConcerns(rows){document.getElementById('concerns-body').innerHTML=rows.length?rows.map(c=>`<tr data-record-row="concerns:${esc(c.id)}"><td>${esc(c.reporter?.fullName||'Unknown')}<br><span class="hint" style="margin:0">${esc(c.reporter?.email||'')}</span></td><td>${esc(c.category)}</td><td>${esc(c.location)}</td><td>${esc(c.description)}</td><td>${fmt(c.createdAt)}</td><td><select class="status-control" data-concern-status="${esc(c.id)}" data-current="${esc(c.status)}">${transitionOptions(c.status,CONCERN_TRANSITIONS,CONCERN_STATUS_LABEL)}</select></td><td>${historyButton('concerns',c.id)}</td><td><button type="button" class="btn btn--green" data-save-concern="${esc(c.id)}">Save</button></td></tr>`).join(''):'<tr><td colspan="8" class="empty-row">No concerns yet.</td></tr>';}
async function loadUsers(){try{const data=await getAdminUsers(),rows=data?.users||data?.results||(Array.isArray(data)?data:[]);document.getElementById('users-body').innerHTML=rows.length?rows.map(u=>`<tr data-record-row="residents:${esc(u.id)}"><td>${esc(u.fullName||u.name||'—')}</td><td>${esc(u.email||'—')}</td><td>${esc(u.role||'—')}</td><td>${fmt(u.createdAt)}</td><td>${historyButton('residents',u.id)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty-row">No residents on file yet.</td></tr>';}catch{document.getElementById('users-error').hidden=false;}finally{document.getElementById('users-loading').hidden=true;}}
async function loadNotices(){document.getElementById('notices-loading').hidden=false;try{const data=await getNotices(),rows=data?.notices||data?.results||(Array.isArray(data)?data:[]);document.getElementById('notices-body').innerHTML=rows.length?rows.map(n=>`<tr data-record-row="notices:${esc(n.id)}"><td>${esc(n.title||'—')}</td><td>${esc(n.category||'—')}</td><td>${fmt(n.publishedAt||n.createdAt)}</td><td>${fmt(n.expiresAt)}</td><td>${historyButton('notices',n.id)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty-row">No notices on file.</td></tr>';}catch(e){document.getElementById('notices-body').innerHTML=`<tr><td colspan="5" class="empty-row">${esc(e.message)}</td></tr>`;}finally{document.getElementById('notices-loading').hidden=true;}}
async function loadOfficials(){document.getElementById('officials-loading').hidden=false;try{const data=await getOfficials(),rows=data?.officials||data?.results||(Array.isArray(data)?data:[]);document.getElementById('officials-body').innerHTML=rows.length?rows.map(o=>`<tr data-record-row="officials:${esc(o.id)}"><td>${esc(o.name||'—')}</td><td>${esc(o.position||'—')}</td><td>${esc(o.committee||'—')}</td><td>${dateOnly(o.termStart)} – ${dateOnly(o.termEnd)}</td><td>${historyButton('officials',o.id)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty-row">No officials on file.</td></tr>';}catch(e){document.getElementById('officials-body').innerHTML=`<tr><td colspan="5" class="empty-row">${esc(e.message)}</td></tr>`;}finally{document.getElementById('officials-loading').hidden=true;}}
const activityState={period:'today',start:null,end:null,actorUserId:'',module:'',action:''};
function dayStart(d){const x=new Date(d);x.setHours(0,0,0,0);return x;}function dayEnd(d){const x=new Date(d);x.setHours(23,59,59,999);return x;}
function periodBounds(period){const now=new Date();if(period==='today')return[dayStart(now),dayEnd(now)];if(period==='week'){const s=dayStart(now),dow=(s.getDay()+6)%7;s.setDate(s.getDate()-dow);const e=dayEnd(s);e.setDate(e.getDate()+6);return[s,e];}if(period==='month')return[new Date(now.getFullYear(),now.getMonth(),1,0,0,0,0),new Date(now.getFullYear(),now.getMonth()+1,0,23,59,59,999)];return[activityState.start,activityState.end];}
function fillSelect(id,items,valueOf,labelOf){const el=document.getElementById(id),current=el.value,first=el.options[0].outerHTML;el.innerHTML=first+items.map(x=>`<option value="${esc(valueOf(x))}">${esc(labelOf(x))}</option>`).join('');el.value=[...el.options].some(o=>o.value===current)?current:'';}
async function loadActivity(){const[start,end]=periodBounds(activityState.period);if(!start||!end)return;document.getElementById('activity-loading').hidden=false;try{const data=await getAdminActivity({start:start.toISOString(),end:end.toISOString(),actorUserId:activityState.actorUserId,module:activityState.module,action:activityState.action});fillSelect('activity-admin',data.filters?.admins||[],x=>x.id,x=>`${x.fullName}${x.staffId?` · ${x.staffId}`:''}`);fillSelect('activity-module',data.filters?.modules||[],x=>x,x=>x.replaceAll('_',' '));fillSelect('activity-action',data.filters?.actions||[],x=>x,x=>x.replaceAll('_',' '));const warning=document.getElementById('activity-warning');warning.hidden=!data.truncated;warning.className='page-alert';warning.textContent=data.truncated?`Showing the newest ${data.count} of ${data.total} matching events. Narrow the filters to see a complete set.`:'';document.getElementById('activity-list').innerHTML=(data.events||[]).length?data.events.map(e=>`<article class="activity-entry"><div><strong>${esc(e.actorName)}</strong> <span class="hint">${e.actorStaffId?`· ${esc(e.actorStaffId)} `:''}· ${fmt(e.createdAt)}</span></div><div>${esc(e.action.replaceAll('_',' '))} · <strong>${esc(e.module)}</strong>${e.recordLabel?` · ${esc(e.recordLabel)}`:''}</div>${e.note?`<div class="hint">${esc(e.note)}</div>`:''}<div class="activity-entry__actions"><button type="button" class="btn btn--green" data-open-record="${esc(e.module)}" data-record-id="${esc(e.recordId)}">Open Record</button>${historyButton(e.module,e.recordId)}</div></article>`).join(''):'<p class="hint">No activity in this period.</p>';}catch(e){showAlert(e.message,'error');}finally{document.getElementById('activity-loading').hidden=true;}}
function eventChange(event){const before=event.before?.status,after=event.after?.status;if(before||after)return`${before?esc(before.replaceAll('_',' ')):'created'} → ${after?esc(after.replaceAll('_',' ')):'—'}`;return esc(event.action.replaceAll('_',' '));}
async function openHistory(module,id){const drawer=document.getElementById('history-drawer'),content=document.getElementById('history-content');drawer.hidden=false;document.getElementById('history-title').textContent=`${module.replaceAll('_',' ')} history`;content.innerHTML='<p class="hint">Loading history…</p>';try{const data=await getAdminRecordHistory(module,id);content.innerHTML=(data.events||[]).length?`<div class="history-timeline">${data.events.map(x=>`<div class="history-line"><strong>${esc(x.actorName)}</strong> · ${eventChange(x)}<br><span class="hint">${esc(x.action.replaceAll('_',' '))} · ${fmt(x.createdAt)}${x.note?` · ${esc(x.note)}`:''}</span></div>`).join('')}</div>`:'<p class="hint">No shared history yet.</p>';}catch(e){content.innerHTML=`<p class="page-alert page-alert--error">${esc(e.message)}</p>`;}}
function closeHistory(){document.getElementById('history-drawer').hidden=true;}
async function openAffectedRecord(module,id){if(!['residents','requests','concerns','notices','officials'].includes(module)){await openHistory(module,id);return;}showPanel(module);const row=document.querySelector(`[data-record-row="${CSS.escape(module+':'+id)}"]`);if(row){document.querySelectorAll('.record-focus').forEach(x=>x.classList.remove('record-focus'));row.classList.add('record-focus');row.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>row.classList.remove('record-focus'),3500);}else{showAlert('The affected record is no longer in the current list. Opening its retained history instead.','error');await openHistory(module,id);}}

let claimStream=null,claimScanTimer=null,currentClaim=null;
function claimStatusLabel(status){return REQUEST_STATUS_LABEL[status]||status;}
function renderClaimResult(data){currentClaim=data?.claim||null;const t=document.getElementById('claim-result');if(!currentClaim){t.innerHTML='<p class="hint">No claim loaded.</p>';return;}const c=currentClaim;const release=data.canRelease?`<button class="btn btn--green" type="button" data-release-claim="${esc(c.id)}">Release Document / Mark Claimed</button>`:`<button class="btn btn--ghost" type="button" disabled>${c.status==='completed'?'Already Released':'Not Ready for Release'}</button>`;t.innerHTML=`<article class="claim-card"><div class="claim-card__head"><div><p class="eyebrow">Claim ${esc(c.trackingNumber||c.id)}</p><h3>${esc(c.documentType)}</h3></div><span class="badge badge--${esc(c.status)}">${esc(claimStatusLabel(c.status))}</span></div><dl class="claim-details"><div><dt>Resident</dt><dd>${esc(c.requestor?.fullName||'—')}</dd></div><div><dt>Email</dt><dd>${esc(c.requestor?.email||'—')}</dd></div><div><dt>Contact</dt><dd>${esc(c.requestor?.contactNumber||'—')}</dd></div><div><dt>Purpose</dt><dd>${esc(c.purpose||'—')}</dd></div><div><dt>Filed</dt><dd>${fmt(c.createdAt)}</dd></div></dl><div class="quick-actions">${release}${historyButton('requests',c.id)}</div><p class="hint">Verification does not change status. Release requires the explicit button above.</p></article>`;}
async function lookupClaim(params){const t=document.getElementById('claim-result');t.innerHTML='<p class="hint">Verifying claim…</p>';try{const data=await resolveAdminClaim(params);renderClaimResult(data);return data;}catch(e){currentClaim=null;t.innerHTML=`<p class="page-alert page-alert--error">${esc(e.message)}</p>`;return null;}}
async function stopClaimCamera(){if(claimScanTimer){clearTimeout(claimScanTimer);claimScanTimer=null;}if(claimStream){claimStream.getTracks().forEach(t=>t.stop());claimStream=null;}const v=document.getElementById('claim-camera');v.srcObject=null;v.hidden=true;document.getElementById('claim-camera-stop').hidden=true;document.getElementById('claim-camera-start').hidden=false;}
async function startClaimCamera(){if(!('BarcodeDetector'in window)||!navigator.mediaDevices?.getUserMedia){showAlert('Camera QR scanning is not supported in this browser. Use Claim No. lookup instead.','error');return;}try{const formats=await BarcodeDetector.getSupportedFormats();if(!formats.includes('qr_code'))throw new Error('QR scanning is not supported by this browser.');const detector=new BarcodeDetector({formats:['qr_code']});claimStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const v=document.getElementById('claim-camera');v.srcObject=claimStream;v.hidden=false;await v.play();document.getElementById('claim-camera-start').hidden=true;document.getElementById('claim-camera-stop').hidden=false;const scan=async()=>{if(!claimStream)return;try{const codes=await detector.detect(v);if(codes.length){const token=codes[0].rawValue;await stopClaimCamera();await lookupClaim({token});return;}}catch{}claimScanTimer=setTimeout(scan,250);};scan();}catch(e){await stopClaimCamera();showAlert(e.message||'Unable to start QR camera. Use Claim No. lookup instead.','error');}}

document.addEventListener('click',async e=>{const rb=e.target.closest('[data-save-request]'),cb=e.target.closest('[data-save-concern]'),pb=e.target.closest('[data-period]'),hb=e.target.closest('[data-history-module]'),ob=e.target.closest('[data-open-record]'),nb=e.target.closest('[data-nav]'),rel=e.target.closest('[data-release-claim]');try{if(nb){showPanel(nb.dataset.nav);if(nb.dataset.nav==='activity')await loadActivity();if(nb.dataset.nav!=='claims')await stopClaimCamera();}if(rb){const id=rb.dataset.saveRequest,select=document.querySelector(`[data-request-status="${CSS.escape(id)}"]`),status=select.value,current=select.dataset.current,note=document.querySelector(`[data-request-note="${CSS.escape(id)}"]`).value.trim();if(status===current)return showAlert('Choose a next status before saving.','error');if(current==='under_review'&&status==='rejected'&&!note)return showAlert('A reason is required when rejecting a request.','error');rb.disabled=true;await updateRequestStatus(id,status,note);showAlert('Request status updated and recorded in Activity.','ok');await Promise.all([loadDashboard(),loadActivity()]);}if(cb){const id=cb.dataset.saveConcern,select=document.querySelector(`[data-concern-status="${CSS.escape(id)}"]`),status=select.value,current=select.dataset.current;if(status===current)return showAlert('Choose a next status before saving.','error');cb.disabled=true;await updateConcernStatus(id,status);showAlert('Concern status updated and recorded in Activity.','ok');await Promise.all([loadDashboard(),loadActivity()]);}if(pb){activityState.period=pb.dataset.period;document.querySelectorAll('[data-period]').forEach(b=>{b.classList.toggle('btn--green',b===pb);b.classList.toggle('btn--ghost',b!==pb);});document.getElementById('custom-range').hidden=activityState.period!=='custom';if(activityState.period!=='custom')await loadActivity();}if(hb)await openHistory(hb.dataset.historyModule,hb.dataset.historyId);if(ob)await openAffectedRecord(ob.dataset.openRecord,ob.dataset.recordId);if(rel){rel.disabled=true;rel.textContent='Releasing…';try{const data=await releaseAdminClaim(rel.dataset.releaseClaim);renderClaimResult({claim:data.claim,canRelease:false});showAlert('Document released and recorded in Activity.','ok');await Promise.all([loadDashboard(),loadActivity()]);}catch(err){showAlert(err.message,'error');if(currentClaim)await lookupClaim({claimNo:currentClaim.trackingNumber});}}}catch(err){showAlert(err.message,'error');await loadDashboard();}});
['activity-admin','activity-module','activity-action'].forEach(id=>document.getElementById(id).addEventListener('change',e=>{activityState[id.replace('activity-','')==='admin'?'actorUserId':id.replace('activity-','')]=e.target.value;loadActivity();}));
document.getElementById('apply-range').addEventListener('click',()=>{const s=document.getElementById('activity-start').value,e=document.getElementById('activity-end').value;if(!s||!e)return showAlert('Choose both start and end dates.','error');const start=new Date(`${s}T00:00:00`),end=new Date(`${e}T23:59:59.999`);if(end<start)return showAlert('End date must be on or after start date.','error');if(end-start>90*86400000)return showAlert('Custom activity searches are limited to 90 days. Please narrow the date range.','error');activityState.start=start;activityState.end=end;loadActivity();});
document.getElementById('claim-lookup-form').addEventListener('submit',async e=>{e.preventDefault();const claimNo=document.getElementById('claim-number').value.trim();if(!claimNo)return showAlert('Enter a Claim No.','error');await lookupClaim({claimNo});});document.getElementById('claim-camera-start').addEventListener('click',startClaimCamera);document.getElementById('claim-camera-stop').addEventListener('click',stopClaimCamera);
document.getElementById('history-close').addEventListener('click',closeHistory);document.getElementById('history-drawer').addEventListener('click',e=>{if(e.target.id==='history-drawer')closeHistory();});document.getElementById('refresh-btn').addEventListener('click',()=>Promise.all([loadDashboard(),loadUsers(),loadNotices(),loadOfficials(),loadActivity()]));document.getElementById('logout-btn').addEventListener('click',async()=>{await stopClaimCamera();clearSession();location.replace('index.html?mode=admin');});document.addEventListener('admin-auth-ready',e=>{const user=e.detail.user;document.getElementById('welcome-name').textContent=user.fullName;document.getElementById('welcome-staffid').textContent=user.staffId||'—';document.getElementById('welcome-staffid-inline').textContent=user.staffId||'—';Promise.all([loadDashboard(),loadUsers(),loadNotices(),loadOfficials(),loadActivity()]);});
