const REQUEST_STATUS_LABEL={pending:'Pending',under_review:'Under review',approved:'Approved',rejected:'Rejected',ready_for_pickup:'Ready for pickup',completed:'Completed'};
const CONCERN_STATUS_LABEL={open:'Open',in_progress:'In progress',resolved:'Resolved',closed:'Closed'};
let requestsCache=[],concernsCache=[],currentUser=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmtDate(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('en-PH',{month:'short',day:'numeric',year:'numeric'});}
function fmtDateTime(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('en-PH');}
function badge(status,map){const key=String(status||'').toLowerCase();return`<span class="badge badge--${esc(key)}">${esc(map[key]||status||'Pending')}</span>`;}
function showPageAlert(message,tone){const box=document.getElementById('portal-alert');box.textContent=message;box.className=`page-alert page-alert--${tone}`;box.hidden=false;clearTimeout(showPageAlert._t);showPageAlert._t=setTimeout(()=>box.hidden=true,4500);}
function goToTab(tabId){document.querySelectorAll('.portal-nav__item').forEach(i=>{const a=i.dataset.tab===tabId;i.classList.toggle('portal-nav__item--active',a);i.setAttribute('aria-selected',a?'true':'false');});document.querySelectorAll('.portal-panel').forEach(p=>p.hidden=p.id!==`panel-${tabId}`);history.replaceState(null,'',`#${tabId}`);}
function initNav(){document.querySelectorAll('.portal-nav__item').forEach(i=>i.addEventListener('click',()=>goToTab(i.dataset.tab)));document.querySelectorAll('[data-goto]').forEach(el=>el.addEventListener('click',()=>goToTab(el.dataset.goto)));goToTab(location.hash.replace('#','')||'dashboard');}
async function loadRequestsAndConcerns(){const[rd,cd]=await Promise.all([getMyRequests(),getMyConcerns()]);requestsCache=rd?.requests||[];concernsCache=cd?.concerns||[];renderDashboard();renderRequestsTable();renderConcernsTable();}
function renderDashboard(){const active=requestsCache.filter(r=>!['completed','rejected'].includes(r.status)),open=concernsCache.filter(c=>!['resolved','closed'].includes(c.status));document.getElementById('metric-requests').textContent=requestsCache.length;document.getElementById('metric-active-requests').textContent=active.length;document.getElementById('metric-open-concerns').textContent=open.length;const att=[...active.slice(0,3).map(r=>({label:`${r.documentType} — ${REQUEST_STATUS_LABEL[r.status]||r.status}`,meta:`Filed ${fmtDate(r.createdAt)} · ${r.trackingNumber||r.id}`,goto:'requests'})),...open.slice(0,3).map(c=>({label:`${c.category} — ${CONCERN_STATUS_LABEL[c.status]||c.status}`,meta:`Reported ${fmtDate(c.createdAt)} · ${c.location||'No location given'}`,goto:'concerns'}))].slice(0,4);const el=document.getElementById('attention-list');el.innerHTML=att.length?att.map(a=>`<div class="attention-item"><div><span class="attention-item__label">${esc(a.label)}</span><span class="attention-item__meta">${esc(a.meta)}</span></div><button type="button" class="btn btn--ghost" data-goto="${a.goto}">View</button></div>`).join(''):'<p class="hint">Nothing needs your attention right now — everything on file is closed out.</p>';el.querySelectorAll('[data-goto]').forEach(x=>x.addEventListener('click',()=>goToTab(x.dataset.goto)));}
function getRejectionNote(r){return(r.history||[]).slice().reverse().find(h=>h.toStatus==='rejected')?.note||null;}
function getReadyForPickupEvent(r){return(r.history||[]).slice().reverse().find(h=>h.toStatus==='ready_for_pickup')||null;}
function renderRequestsTable(){const b=document.getElementById('requests-body');b.innerHTML=requestsCache.length?requestsCache.map(r=>{const note=getRejectionNote(r);const action=r.status==='ready_for_pickup'?`<button type="button" class="btn btn--ghost" data-download-stub="${esc(r.id)}">Download Claim Stub + QR</button>`:'—';return`<tr><td><strong>${esc(r.documentType)}</strong></td><td>${esc(r.purpose)}</td><td>${fmtDateTime(r.createdAt)}</td><td>${badge(r.status,REQUEST_STATUS_LABEL)}</td><td>${esc(r.trackingNumber||r.id||'—')}</td><td>${note?esc(note):'—'}</td><td>${action}</td></tr>`;}).join(''):'<tr><td colspan="7" class="empty-row">You have not submitted any document requests yet.</td></tr>';}
function renderConcernsTable(){const b=document.getElementById('concerns-body');b.innerHTML=concernsCache.length?concernsCache.map(c=>`<tr><td>${esc(c.category)}</td><td>${esc(c.location||'—')}</td><td>${esc(c.description)}</td><td>${fmtDateTime(c.createdAt)}</td><td>${badge(c.status,CONCERN_STATUS_LABEL)}</td><td>${c.status==='resolved'?`<button type="button" class="btn btn--green" data-confirm-resolved="${esc(c.id)}">Confirm Resolved</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="6" class="empty-row">You have not reported any concerns yet.</td></tr>';}
async function refreshAll(){try{await loadRequestsAndConcerns();}catch(err){if(err.status===401){clearSession();location.replace('index.html?expired=1');return;}showPageAlert(err.message,'error');}}
async function renderOfficials(){const t=document.getElementById('officials-grid');try{const d=await getOfficials(),rows=d?.officials||[];t.innerHTML=rows.length?rows.map(o=>`<article class="id-card"><div class="id-card__role">${esc(o.position||'')}</div><div class="id-card__name">${esc(o.name||'')}</div><div class="id-card__contact">${esc(o.contactNumber||o.contact||'')}</div></article>`).join(''):'<p class="hint">No officials have been published yet.</p>';}catch{t.innerHTML='<p class="hint">The directory is temporarily unavailable.</p>';}}
async function renderNotices(){const t=document.getElementById('notices-board');try{const d=await getNotices(),rows=d?.notices||[];t.innerHTML=rows.length?rows.map((n,i)=>`<article class="notice notice--${i%3===0?'green':i%3===1?'orange':'gold'}"><div class="notice__title">${esc(n.title)}</div><div class="notice__body">${esc(n.body||n.content||'')}</div><span class="notice__date">Posted ${fmtDate(n.publishedAt||n.createdAt)}</span></article>`).join(''):'<p class="hint">No notices have been published yet.</p>';}catch{t.innerHTML='<p class="hint">The notice board is temporarily unavailable.</p>';}}
async function drawQr(canvas,token,width=150){if(!window.QRCode||!token)throw new Error('QR renderer unavailable.');await QRCode.toCanvas(canvas,token,{width,margin:1,errorCorrectionLevel:'M'});}
async function renderStub(request){document.getElementById('stub-placeholder').hidden=true;const out=document.getElementById('stub-output');out.innerHTML=`<div class="stub claim-stub-screen"><div class="claim-stub-screen__body"><div class="stub__eyebrow">Claim stub</div><div class="stub__doc">${esc(request.documentType)}</div><div class="stub__row"><span>Purpose</span><span>${esc(request.purpose)}</span></div><div class="stub__row"><span>Claim No.</span><span class="stub__tracking">${esc(request.trackingNumber||request.id)}</span></div><div class="stub__row"><span>Date filed</span><span>${fmtDate(request.createdAt)}</span></div></div><div class="claim-stub-screen__qr"><canvas id="claim-stub-qr" aria-label="Claim QR code"></canvas><small>Scan at barangay hall</small></div></div><p class="hint">Present this stub or QR code when claiming your document. Claim No. remains available as a manual fallback.</p>`;try{await drawQr(document.getElementById('claim-stub-qr'),request.claimToken,150);}catch(e){showPageAlert(e.message,'error');}}
function initForms(){document.getElementById('request-form').addEventListener('submit',async ev=>{ev.preventDefault();const btn=ev.target.querySelector('button[type="submit"]');btn.disabled=true;btn.textContent='Submitting…';try{const res=await createRequest({documentType:document.getElementById('doc-type').value,purpose:document.getElementById('doc-purpose').value.trim()});await renderStub(res?.request||res);await refreshAll();ev.target.reset();}catch(err){showPageAlert(err.message||'Unable to submit your request.','error');}finally{btn.disabled=false;btn.textContent='Submit request';}});document.getElementById('report-form').addEventListener('submit',async ev=>{ev.preventDefault();const btn=ev.target.querySelector('button[type="submit"]');btn.disabled=true;btn.textContent='Submitting…';try{await createConcern({category:document.getElementById('report-type').value,location:document.getElementById('report-location').value.trim(),description:document.getElementById('report-desc').value.trim()});showPageAlert('Concern reported. You can track it under My Concerns.','ok');await refreshAll();ev.target.reset();}catch(err){showPageAlert(err.message||'Unable to submit your concern.','error');}finally{btn.disabled=false;btn.textContent='Submit report';}});}
function wrapCanvasText(ctx,text,x,y,maxWidth,lineHeight){const words=text.split(' ');let line='';for(const word of words){const test=`${line}${word} `;if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line,x,y);line=`${word} `;y+=lineHeight;}else line=test;}ctx.fillText(line,x,y);}
async function generateClaimStubCanvas(request){const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=560;const ctx=canvas.getContext('2d');ctx.fillStyle='#F8F5EE';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#1F5C43';ctx.fillRect(0,0,canvas.width,110);ctx.fillStyle='#FFFFFF';ctx.font='700 28px Georgia, serif';ctx.fillText('Barangay San Isidro',40,48);ctx.font='600 15px Arial';ctx.fillStyle='#DDEFE6';ctx.fillText('DOCUMENT CLAIM STUB',40,78);const ready=getReadyForPickupEvent(request),rows=[['Resident name',currentUser?.fullName||'—'],['Document type',request.documentType],['Claim No.',request.trackingNumber||request.id],['Date filed',fmtDate(request.createdAt)],['Ready for pickup',ready?fmtDate(ready.createdAt):'—'],['Processing Staff ID',ready?.actorStaffId||'—']];let y=155;for(const[label,value]of rows){ctx.font='600 12px Arial';ctx.fillStyle='#5B6570';ctx.fillText(label.toUpperCase(),40,y);ctx.font='600 20px Arial';ctx.fillStyle='#1B1F23';ctx.fillText(String(value),40,y+26);y+=58;}const qr=document.createElement('canvas');await drawQr(qr,request.claimToken,220);ctx.drawImage(qr,740,155,220,220);ctx.font='600 13px Arial';ctx.fillStyle='#1B1F23';ctx.fillText('SCAN TO VERIFY CLAIM',770,398);ctx.font='italic 13px Arial';ctx.fillStyle='#5B6570';wrapCanvasText(ctx,'Present this stub or QR code when claiming your document. Staff must explicitly confirm release; scanning alone does not change status.',40,520,900,18);return canvas;}
async function downloadClaimStub(request){try{const canvas=await generateClaimStubCanvas(request);canvas.toBlob(blob=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${request.trackingNumber||request.id}-claim-stub.png`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);},'image/png');}catch(e){showPageAlert(e.message||'Unable to generate claim stub.','error');}}
async function handleConfirmResolved(id,button){const original=button.textContent;button.disabled=true;button.textContent='Confirming…';try{await confirmConcernResolved(id);showPageAlert('Thanks — concern marked closed.','ok');await refreshAll();}catch(err){showPageAlert(err.message||'Unable to confirm resolution.','error');button.disabled=false;button.textContent=original;}}
document.addEventListener('click',async e=>{const d=e.target.closest('[data-download-stub]'),r=e.target.closest('[data-confirm-resolved]');if(d){const req=requestsCache.find(x=>x.id===d.dataset.downloadStub);if(req)await downloadClaimStub(req);}if(r)await handleConfirmResolved(r.dataset.confirmResolved,r);});
document.getElementById('logout-btn').addEventListener('click',()=>{clearSession();location.replace('index.html');});initNav();initForms();renderOfficials();renderNotices();document.addEventListener('member-auth-ready',e=>{currentUser=e.detail.user;document.getElementById('welcome-name').textContent=currentUser.fullName;document.getElementById('resident-email').textContent=currentUser.email;refreshAll();});
